# Conexão com o Banco de Dados Postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/CrudBancoSpring
spring.datasource.username=postgres
spring.datasource.password=0509

# Configuração do Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
